version: "3.8"

services:
  ogres-audition:
    build: .
    ports:
      - "1337:1337"
    environment:
      - FLAG=FantasyCTF{sh3_s4id_d0_y0u_kn0w_th3_muffin_m4n}
      - SIMILARITY_THRESHOLD=0.70
    restart: unless-stopped
