services:
  whispering-merchant:
    build:
      context: ..
      dockerfile: The-Whispering-Merchant-Easy/Dockerfile
    ports:
      - "7002:8000"
    environment:
      - FLAG=FantasyCTF{m3rch4nt_t0ngu3_sl1pp3d}
      - GEMINI_API_KEY=${AIzaSyA3c8soFbMzduOSaN9cwqZuWnvuhhIzxq4}
      - GEMINI_MODEL=gemini-2.5-flash
      - RATE_LIMIT=30
    restart: unless-stopped
